Release:
	g++-4.9 -Wall -pthread -Wextra -O2 -std=c++14 *.cpp ./Utils/*.cpp -lglut -lGL -lGLEW -lGLU -lm
Debug:
	g++-4.9 -Wall -pthread -Wextra -ggdb -std=c++14 *.cpp ./Utils/*.cpp -lglut -lGL -lGLEW -lGLU -lm
