Release:
	g++-4.9 -Wall -Wextra -O2 -std=c++14 *.cpp -lglut -lGL -lGLEW -lGLU -lm -lpthread -ILU -lILUT -lIL
Debug:
	g++-4.9 -Wall -Wextra -ggdb -std=c++14 *.cpp -lglut -lGL -lGLEW -lGLU -lm -lpthread -ILU -lILUT -lIL
